<?php

//create main menu item
function DNA_checker_menu() {
    $items['DNA_checker'] = array(
        'title' => 'DNA Checker',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('DNA_checker_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['DNA_checker_output'] = array(
        'title' => 'DNA Checker Results',
        'page callback' => 'DNA_checker_output',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function DNA_checker_form() {
    $form['DNA_first'] = array(
        '#title' => 'DNA',
        '#type' => 'textfield',
        '#description' => t('Input DNA sequence'),
        '#element_validate' => array('element_validate_characters'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt',
    );
    return $form;
}


function element_validate_characters($element) {
    if(preg_match('/[^ATCGatcg]/', $element['#value'])) {
        form_error($element, t('Phrase may only contain characters a,t,c, and g'));
    }
}

function DNA_converter($DNA) {
  $DNA = str_split(strtolower($DNA));
  $DNA_result = array();
  for ($i=0; $i <= count($DNA) - 1 ; $i++) {
    if ($DNA[$i] == 'a') {
      array_push($DNA_result, 't');
    } elseif ($DNA[$i] == 't') {
      array_push($DNA_result, 'a');
    } elseif ($DNA[$i] == 'c') {
      array_push($DNA_result, 'g');
    } elseif ($DNA[$i] == 'g') {
    array_push($DNA_result, 'c');
    }
  }
  return join($DNA_result);
}

function DNA_checker_form_submit($form, &$form_state) {
    $DNA_first = $form_state['values']['DNA_first'];
    $DNA_second = DNA_converter($DNA_first);
    $_SESSION['DNA_second'] = $DNA_second;
    $form_state['redirect'] = 'DNA_checker_output';
}

function DNA_checker_output() {
    return $_SESSION['DNA_second'];

}
